import type { Localized, UiCopy } from '../types.ts'

export const ui: Localized<UiCopy> = {
  ru: {
    skip: 'К материалам',
    edition: 'Московский выпуск',
    tagline: 'Сводка дня: ставка, город, лаборатория',
    volume: 'Том 28 · № 239',
    masthead: 'АТЛАС',
    mastheadSub: 'ежедневная газета',
    publisher: 'Редакция «АТЛАС»',
    readFull: 'Читать целиком',
    updated: 'Обновлено',
    bylinePrefix: 'Текст',
    search: 'Поиск по выпуску',
    searchPlaceholder: 'Заголовок или фамилия',
    searchSubmit: 'Найти',
    noResults: 'В этом выпуске совпадений нет.',
    latest: 'Ещё в номере',
    leadKicker: 'Главный материал',
    markets: 'Котировки на 11:00 МСК',
    weather: 'Бюро погоды',
    subscribe: 'Бумажный номер',
    subscribeHint: 'Шесть дней, доставка до 7:30, Москва и область',
    subscribePrice: '1 490 ₽ в месяц',
    imprint: 'Учредитель — редакция «АТЛАС». Свидетельство ПИ № ФС77-44291.',
    address: 'Москва, Лубянский проезд, 15, стр. 2',
    correction: 'Сообщить об ошибке: desk@atlas.press',
    print: 'Для печати',
    related: 'По теме',
    authorAlso: 'Другие материалы автора',
    minutes: 'мин',
    menu: 'Рубрики',
    closeMenu: 'Закрыть',
    home: 'На первую',
    notFound: 'Этой полосы в номере нет',
    notFoundHint: 'Проверьте адрес или вернитесь к первой полосе выпуска.',
    offline: 'Нет связи с редакционным сервером.',
    retry: 'Запросить снова',
    editionsLabel: 'Выпуски',
    todayLock: 'Закрытие полосы — 11:00 МСК',
    briefsTitle: 'Короткой строкой',
    sciencePack: 'Наука',
    cityPack: 'Город',
    culturePack: 'Культура',
    commentPack: 'Колонка',
    footerDesk: 'Дежурная служба 05:00–23:00',
    issn: 'ISSN 1562-4412',
    sections: {
      politics: 'Политика',
      business: 'Экономика',
      city: 'Город',
      science: 'Наука',
      culture: 'Культура',
      comment: 'Мнения',
    },
  },
  en: {
    skip: 'Skip to stories',
    edition: 'London edition',
    tagline: 'Business, the city, and the lab — six days',
    volume: 'Vol. 28 · No. 239',
    masthead: 'ATLAS',
    mastheadSub: 'a daily paper',
    publisher: 'Atlas Desk Ltd',
    readFull: 'Continue reading',
    updated: 'Updated',
    bylinePrefix: 'By',
    search: 'Search this edition',
    searchPlaceholder: 'Headline or byline',
    searchSubmit: 'Search',
    noResults: 'Nothing in this edition matches.',
    latest: 'Also in the paper',
    leadKicker: 'The splash',
    markets: 'Prices at 09:00 BST',
    weather: 'Bureau weather',
    subscribe: 'Home delivery',
    subscribeHint: 'Six days a week, on the mat by 07:00, Greater London',
    subscribePrice: '£18 a month',
    imprint: 'Published by Atlas Desk Ltd. Company no. 4419281.',
    address: '41 Clerkenwell Road, London EC1M 5RS',
    correction: 'Corrections: desk@atlas.press',
    print: 'Print view',
    related: 'Related',
    authorAlso: 'More by this reporter',
    minutes: 'min',
    menu: 'Sections',
    closeMenu: 'Close',
    home: 'Front page',
    notFound: 'This page is not in the paper',
    notFoundHint: 'Check the address or go back to the front page of this edition.',
    offline: 'The newsroom server is not answering.',
    retry: 'Try again',
    editionsLabel: 'Editions',
    todayLock: 'Page lock 09:00 BST',
    briefsTitle: 'In brief',
    sciencePack: 'Science',
    cityPack: 'City',
    culturePack: 'Culture',
    commentPack: 'Comment',
    footerDesk: 'Newsdesk 04:00–22:00',
    issn: 'ISSN 1562-4412',
    sections: {
      politics: 'Politics',
      business: 'Business',
      city: 'City',
      science: 'Science',
      culture: 'Culture',
      comment: 'Comment',
    },
  },
  zh: {
    skip: '跳至正文',
    edition: '上海版',
    tagline: '盯工厂、码头和市政账本的日报',
    volume: '第28卷 · 第239期',
    masthead: '经纬',
    mastheadSub: '日报',
    publisher: '经纬日报社',
    readFull: '全文',
    updated: '更新于',
    bylinePrefix: '记者',
    search: '检索本期',
    searchPlaceholder: '标题或记者',
    searchSubmit: '检索',
    noResults: '本期没有相符条目。',
    latest: '本期还有',
    leadKicker: '头版',
    markets: '北京时间16:00报价',
    weather: '本报气象',
    subscribe: '纸质报',
    subscribeHint: '周一至周六，内环内晨7时前送达',
    subscribePrice: '98元/月',
    imprint: '经纬日报社主办  沪报出证字第44192号',
    address: '上海市黄浦区中山南路168号',
    correction: '勘误来信 desk@atlas.press',
    print: '打印',
    related: '相关报道',
    authorAlso: '记者近期稿件',
    minutes: '分钟',
    menu: '栏目',
    closeMenu: '关闭',
    home: '头版',
    notFound: '本期无此版面',
    notFoundHint: '请核对地址，或返回本期头版。',
    offline: '编辑部服务器无应答。',
    retry: '再试一次',
    editionsLabel: '各版',
    todayLock: '截稿 北京时间16:00',
    briefsTitle: '简讯',
    sciencePack: '科学',
    cityPack: '市政',
    culturePack: '文化',
    commentPack: '评论',
    footerDesk: '夜班 4:00–22:00',
    issn: '国际刊号 1562-4412',
    sections: {
      politics: '时政',
      business: '经济',
      city: '市政',
      science: '科学',
      culture: '文化',
      comment: '评论',
    },
  },
}

export const ticker: Localized<{ label: string; value: string; change: string; up: boolean }[]> = {
  ru: [
    { label: 'IMOEX', value: '2 784,12', change: '+0,41%', up: true },
    { label: 'USD/RUB', value: '91,35', change: '−0,22', up: false },
    { label: 'Brent', value: '$78,40', change: '+0,85', up: true },
    { label: 'пшеница FOB', value: '$228', change: '+6', up: true },
  ],
  en: [
    { label: 'FTSE 100', value: '8 241.6', change: '−0.18%', up: false },
    { label: 'Brent', value: '$78.40', change: '+0.85', up: true },
    { label: 'GBP/USD', value: '1.274', change: '+0.003', up: true },
    { label: 'SSE Comp', value: '3 012.8', change: '+0.62%', up: true },
  ],
  zh: [
    { label: '上证综指', value: '3 012.8', change: '+0.62%', up: true },
    { label: '布伦特', value: '$78.40', change: '+0.85', up: true },
    { label: '在岸人民币', value: '7.128', change: '−0.012', up: false },
    { label: 'BDI', value: '1 864', change: '+27', up: true },
  ],
}

export const weather: Localized<{ city: string; temp: string; note: string }[]> = {
  ru: [
    { city: 'Москва', temp: '+18°', note: 'пасмурно, 748 мм' },
    { city: 'Новороссийск', temp: '+24°', note: 'ветер з-ю-з, 8 м/с' },
    { city: 'Тикси', temp: '+6°', note: 'морось' },
  ],
  en: [
    { city: 'London', temp: '16°C', note: 'drizzle, 1011 hPa' },
    { city: 'Istanbul', temp: '29°C', note: 'haze, S 4 m/s' },
    { city: 'Moscow', temp: '18°C', note: 'overcast' },
  ],
  zh: [
    { city: '上海', temp: '31°C', note: '多云，南风3级' },
    { city: '武汉', temp: '34°C', note: '晴，汉口流量偏枯' },
    { city: '伦敦', temp: '16°C', note: '小雨' },
  ],
}

export const briefs: Localized<{ title: string; text: string }[]> = {
  ru: [
    {
      title: 'ОСАГО отложили',
      text: 'Комитет Госдумы по транспорту перенёс слушания по тарифу ОСАГО на 3 сентября. Повестка — территориальные коэффициенты, не база.',
    },
    {
      title: 'Сгущёнка с полки',
      text: 'Роспотребнадзор снял 12 тыс. банок партии от 14 августа, завод в Белгородской области. Причина — негерметичный шов, не состав.',
    },
    {
      title: 'Баумана до 22:00',
      text: 'В Казани до 22:00 перекроют участок ул. Баумана: меняют чугун 1961 года. Обход — через Профсоюзную, два светофора.',
    },
  ],
  en: [
    {
      title: 'Ofcom and the prize draw',
      text: 'Ofcom has opened a file on a breakfast-radio prize after 11,000 duplicate entries from one IP block. The station pulled the draw at 07:12.',
    },
    {
      title: 'Mogden spill fine',
      text: 'Thames Water was fined £4.2m for a March sewage spill at Mogden. The judge sat for two hours; the company did not appeal in court.',
    },
    {
      title: 'Rail freight paths',
      text: 'A Commons committee will take evidence on rail freight paths on 9 September. Hauliers want night windows kept after the autumn timetable.',
    },
  ],
  zh: [
    {
      title: '锂盐两家接函',
      text: '上交所对两家锂盐公司下发监管函，要求五日之内说明库存口径是否含委托加工。函件未点名价格，点的是记账。',
    },
    {
      title: '锚地夜航缩短',
      text: '黄浦江一号锚地自今日起夜航窗口由六小时改为四小时。港务称是能见度，引水说是船时。',
    },
    {
      title: '实验室名单',
      text: '市教委公布十七所中学化学实验室改造名单，工期至2027年9月1日。四所仍用上世纪七十年代通风柜，见市政版。',
    },
  ],
}

export const dateLabels: Localized<string> = {
  ru: 'среда, 26 августа 2026',
  en: 'Wednesday 26 August 2026',
  zh: '2026年8月26日 星期三',
}

export const editionNames: Localized<string> = {
  ru: 'Русская',
  en: 'English',
  zh: '中文',
}
